name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  smoketests:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
      # 4.2.2
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false

    - name: Install flatpak and flatpak-builder
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends flatpak \
            elfutils flatpak-builder dbus-daemon

    - name: Set up flathub remote
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Allow file:// clones with git>=2.38.1
      run: |
        git config --global protocol.file.allow always

    - name: Prepare for hashing
      run: |
        flatpak-builder --show-manifest org.flatpak.Builder.json >> org.flatpak.Builder-cache.json

      # 4.2.2
    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
      with:
        path: ${{ github.workspace }}/.flatpak-builder
        key: ${{ runner.os }}-flatpak-builder-${{ hashFiles('org.flatpak.Builder-cache.json') }}
        restore-keys: ${{ runner.os }}-flatpak-builder-

    - name: Build org.flatpak.Builder
      run: |
        flatpak-builder --verbose --user --sandbox --force-clean \
          --repo=repo \
          --state-dir="$GITHUB_WORKSPACE/.flatpak-builder" \
          --install-deps-from=flathub --default-branch=localtest \
          --ccache --keep-build-dirs --install builddir \
          org.flatpak.Builder.json

    - name: Check if org.flatpak.Builder launches
      run: |
        flatpak run org.flatpak.Builder//localtest --version

    - name: Check if appstreamcli launches
      run: |
        flatpak run --command=appstreamcli org.flatpak.Builder//localtest vercmp 1 2

    - name: Check if just launches
      run: |
        flatpak run --command=just org.flatpak.Builder//localtest --version

    - name: Check if desktop-file-validate launches
      run: |
        flatpak run --command=desktop-file-validate org.flatpak.Builder//localtest --version

    - name: Check if ostree launches
      run: |
        flatpak run --command=ostree org.flatpak.Builder//localtest --version

    - name: Check if 7z works
      run: |
        curl -sL https://github.com/ip7z/7zip/releases/download/24.07/7z2407-src.7z > 7z-src.7z
        flatpak run --filesystem=$(pwd) --command=7z org.flatpak.Builder//localtest x -y 7z-src.7z

    - name: Check if rpm2cpio works
      run: |
        curl -sL https://archives.fedoraproject.org/pub/archive/fedora/linux/core/1/x86_64/os/Fedora/RPMS/bash-2.05b-34.x86_64.rpm > bash.rpm
        flatpak run --filesystem=$(pwd) --command=rpm2cpio org.flatpak.Builder//localtest bash.rpm|cpio -i -d

    - name: Check if git-lfs works
      run: |
        flatpak run --filesystem=$(pwd) --command=git org.flatpak.Builder//localtest lfs env

    - name: Check if svn works
      run: |
        flatpak run --command=svn org.flatpak.Builder//localtest info --depth empty --show-item revision https://svn.code.sf.net/p/freeimage/svn/

    # Needed by flatpak-github-actions
    - name: Check if xvfb-run works
      run: |
        flatpak run --command=xvfb-run org.flatpak.Builder//localtest -a flatpak-builder --version

    - name: Check if xwfb-run works
      run: |
        flatpak run --command=xwfb-run org.flatpak.Builder//localtest --help

    # Needed by flatpak-github-actions
    - name: Check if dbus-daemon works
      run: |
        flatpak run --command=dbus-daemon org.flatpak.Builder//localtest --version

    # Needed by OBS
    - name: Check if gh works
      run: |
        flatpak run --command=gh org.flatpak.Builder//localtest --version

    # Needed by OBS
    - name: Check if jq works
      run: |
        flatpak run --command=jq org.flatpak.Builder//localtest --version

    - name: Check if xmlstarlet works
      run: |
        flatpak run --command=xmlstarlet org.flatpak.Builder//localtest --version

    - name: Check if uv works
      run: |
        flatpak run --command=uv org.flatpak.Builder//localtest --version

    - name: Check if diffoscope works
      run: |
        flatpak run --command=diffoscope org.flatpak.Builder//localtest --version

    - name: Check if binwalk works
      run: |
        flatpak run --command=binwalk org.flatpak.Builder//localtest --version

    - name: Check if fontforge works
      run: |
        flatpak run --command=fontforge org.flatpak.Builder//localtest --version

    - name: Check if xxd works
      run: |
        flatpak run --command=xxd org.flatpak.Builder//localtest --version

    - name: Check if asar works
      run: |
        flatpak run --command=asar org.flatpak.Builder//localtest help

    - name: Check if img2txt works
      run: |
        flatpak run --command=img2txt org.flatpak.Builder//localtest --version

    - name: Check if flathub-repro-checker works
      run: |
        flatpak run --command=flathub-repro-checker org.flatpak.Builder//localtest --version

    - name: Sanity check the linter
      run: |
        flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions manifest org.flatpak.Builder.json
        flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions builddir builddir
        flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions repo repo

    - name: Validate the metainfo file
      run: |
        flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest appstream org.flatpak.Builder.metainfo.xml

    - name: Build org.freedesktop.appstream.cli with org.flatpak.Builder
      run: |
        git clone --depth=1 --branch master --single-branch --recursive https://github.com/flathub/org.freedesktop.appstream.cli.git
        cd org.freedesktop.appstream.cli
        dbus-run-session flatpak run org.flatpak.Builder//localtest \
          --verbose --user --sandbox --force-clean \
          --install-deps-from=flathub --default-branch=localtest \
          --ccache --disable-cache --install builddir \
          org.freedesktop.appstream.cli.yaml

    - name: Build io.neovim.nvim with org.flatpak.Builder
      run: |
        git clone --depth=1 --branch master --recursive --single-branch --recursive https://github.com/flathub/io.neovim.nvim.git
        cd io.neovim.nvim
        dbus-run-session flatpak run org.flatpak.Builder//localtest \
          --verbose --user --sandbox --force-clean \
          --install-deps-from=flathub --default-branch=localtest \
          --ccache --disable-cache \
          --mirror-screenshots-url=https://domain.tld \
          --install builddir io.neovim.nvim.yaml
